{% set name = "opencl-clang" %}
{% set version = "15.0.0" %}
{% set llvm_version = version.split(".")[0] ~ "." ~ version.split(".")[1] %}

package:
  name: intel-opencl-clang
  version: {{ version }}

source:
  url: https://github.com/intel/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ea179674e52bc8c658e2655f76be467f7052f7d2c37ebcfdb102dce645ad1411

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
  host:
    - llvmdev   {{ llvm_version }}
    - llvm      {{ llvm_version }}
    - clangdev  {{ llvm_version }}
    - libclang-cpp  {{ llvm_version }}
    - llvm-spirv   {{ llvm_version }}
  run:
    - {{ pin_compatible("llvm-spirv", exact=True) }}

test:
  commands:
    - test -f ${PREFIX}/lib/libopencl_clang${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/intel/opencl-clang
  license: NCSA
  license_file: LICENSE
  license_family: BSD
  summary: Common clang is a thin wrapper library around clang. Common clang has OpenCL-oriented API and is capable to compile OpenCL C kernels to SPIR-V modules.

extra:
  recipe-maintainers:
    - isuruf
